name: Tests

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '28 0 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ["1.22", "1.23"]
        gel-version: [stable, nightly]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Lint
        uses: golangci/golangci-lint-action@v6.5.0
        with:
          # GREP_FOR_THIS_STRING_WHEN_CHANGING_GOLANGCI_LINT_VERSION
          version: v1.61.0

      - name: Check Formatting
        run: |
          make format
          if [[ "$(git status --porcelain)" != "" ]]; then
            echo "Code is not formatted. Run make format."
            exit 1
          fi

      - name: Check Code Generation
        run: |
          go install
          make gen
          if [[ "$(git status --porcelain)" != "" ]]; then
            echo "Generated code is out of sync. Run make gen."
            exit 1
          fi

      - name: Build
        run: |
          go build .

      - name: Setup WSL
        if: ${{ startswith(matrix.os, 'windows') }}
        uses: vampire/setup-wsl@v1
        with:
          wsl-shell-user: gel
          additional-packages:
            ca-certificates
            curl

      - name: Install Gel
        uses: geldata/setup-gel@v1
        with:
          server-version: ${{ matrix.gel-version }}

      - name: Test
        run: |
          make test

      - name: Exercise Benchmarks
        run: |
          # run micro benchmarks to be sure they still work
          make bench
